nodeLinker: node-modules

npmScopes: 
  kimafinance:
    npmRegistryServer: "https://registry.npmjs.org/"
    npmAuthToken: "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"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-postinstall.cjs
    spec: "https://raw.githubusercontent.com/gravitywelluk/yarn-plugin-postinstall/master/bundles/%40yarnpkg/plugin-postinstall.js"

yarnPath: .yarn/releases/yarn-3.2.3.cjs
