name: Deploy 2

on:
    push:
        branches:
            - dev-mukul
    # allow manual run
    workflow_dispatch:

jobs:
    deploy:
        name: Deploy Release
        runs-on: ubuntu-latest
        steps:
            # DNS
            - name: Update DNS with new IPFS hash
              env:
                  CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
                  CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
                  RECORD_DOMAIN: ${{ secrets.CLOUDFLARE_DOMAIN }}
                  RECORD_NAME: 'fi-qa'
              uses: textileio/cloudflare-update-dnslink@master
              with:
                  cid: 'bafybeibf6fm2gk3khzy3uptnjacnjox5awmizkdqml6f6pufcpjystghcu'
