name: Production Release

on:
    push:
        branches:
            - production
    workflow_dispatch:

jobs:
    bump_version:
        name: Bump Version
        runs-on: ubuntu-latest
        outputs:
            new_tag: ${{ steps.github_tag_action.outputs.new_tag }}
            changelog: ${{ steps.github_tag_action.outputs.changelog }}
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  fetch-depth: '0'
            - name: Bump version and push tag
              id: github_tag_action
              uses: mathieudutour/github-tag-action@v5.5              
              with:
                  default_bump: minor
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  release_branches: production

    deploy:
        name: Deploy Release
        runs-on: ubuntu-latest
        needs: bump_version
        if: ${{ needs.bump_version.outputs.new_tag != null }}
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Set network env(s)
              run: |
                  echo "NETWORK=production" >> $GITHUB_ENV

            - name: Load node v14
              uses: actions/setup-node@v1
              with:
                  node-version: '14'

            - name: Install dependencies
              uses: bahmutov/npm-install@v1

            - name: Build app
              run: yarn build

            # Pinning
            - name: Pin via web3 storage (Upload to web3 storage)
              id: web3
              uses: web3-storage/add-to-web3@v1
              with:
                  web3_token: ${{ secrets.WEB3_STORAGE }}
                  path_to_add: './build'

            - name: Display pin address
              run: |
                  echo published as ${{ steps.web3.outputs.url }}
                  echo cid ${{ steps.web3.outputs.cid }}

            # DNS
            - name: Update DNS with new IPFS hash
              env:
                CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
                RECORD_DOMAIN: "gooddollar.org"
                RECORD_NAME: "_dnslink.fi"
                CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
              id: dnslink
              uses: textileio/cloudflare-update-dnslink@master
              with:
                cid: ${{ steps.web3.outputs.cid }}

            # GitHub release with links
            - name: Create GitHub Release with tag ${{ needs.bump_version.outputs.new_tag }}
              id: create_release
              uses: ncipollo/release-action@v1.8.4
              env:
                  DEPLOY_ADDR: 'fi.gooddollar.org'
              with:
                  tag: ${{ needs.bump_version.outputs.new_tag }}
                  name: ${{ needs.bump_version.outputs.new_tag }}
                  token: ${{ secrets.GITHUB_TOKEN }}
                  body: |
                      IPFS hash of the deployment:
                      - CID: `${{ steps.web3.outputs.cid }}`
                      The latest release is always accessible via our alias to the Cloudflare IPFS gateway at [${{ env.DEPLOY_ADDR }}](https://${{ env.DEPLOY_ADDR }}/).
                      IPFS gateways:
                      - ${{ steps.web3.outputs.url }}
                      - https://${{ steps.web3.outputs.cid }}.ipfs.dweb.link/
                      - https://${{ steps.web3.outputs.cid }}.ipfs.cf-ipfs.com/
                      - https://gateway.pinata.cloud/ipfs/${{ steps.web3.outputs.cid }}/
                      - https://cloudflare-ipfs.com/ipfs/${{ steps.web3.outputs.cid }}/
                      - https://ipfs.io/ipfs/${{ steps.web3.outputs.cid }}/
                      ${{ needs.bump_version.outputs.changelog }}
